

train:
	python run_multi-task_rnn.py --data_dir data/slu --train_dir model_tmp --max_sequence_length 40 --task tagging --bidirectional_rnn True --max_training_steps 20000 --size 182 --word_embedding_size 182 --num_layers 1
